/**
 * Fabric.js canvas singleton for the StrikeForge ball texture pipeline.
 *
 * Authority:
 *   - AAP §0.3.4 / §0.6.7 — "frontend/src/configurator/texture/fabricCanvas.ts
 *     | Fabric.js canvas singleton".
 *   - AAP §0.4.2 — `fabric` ^6.x (modular, ESM `StaticCanvas` API).
 *   - AAP C6 / Rule R7 — texture update order: Fabric `renderAll()` first,
 *     THEN Three `texture.needsUpdate = true`. This module owns the
 *     Fabric side of that contract; `texturePipeline.ts` enforces the
 *     ordering and `threeTexture.ts` owns the Three side.
 *   - QA Report Issue #9 — texture pipeline files MUST exist with the
 *     documented coordination contract.
 *
 * Responsibilities:
 *   1. Lazily create a single off-screen Fabric.js `StaticCanvas` (HTML
 *      `<canvas>` element rendered by Fabric in pure JS — never attached
 *      to the DOM) used as the source bitmap for the Three.js texture.
 *   2. Expose a small typed API (`getFabricCanvas`, `getFabricElement`,
 *      `renderFabricCanvas`, `disposeFabricCanvas`) used by the texture
 *      pipeline and by Sphere.tsx (read-only) — NEVER mutated directly
 *      by feature components.
 *   3. Survive React 18 StrictMode double-invocation and Vite HMR by
 *      tracking module-private singletons rather than per-effect state.
 *
 * Texture dimensions:
 *   The bitmap is sized 1024×512 (a 2:1 spherical-projection-friendly
 *   ratio that wraps the equirectangular sphere texture cleanly with
 *   ample resolution for both panel colors and uploaded logos). Powers
 *   of two are NOT strictly required by WebGL2 (the configurator's
 *   target) but the chosen dimensions are still 2-aligned, ensuring
 *   compatibility if the project ever ships a WebGL1 fallback.
 *
 * Cross-cutting rules enforced here:
 *   - Rule R7 / C6: ZERO direct calls to `THREE.Texture#needsUpdate`.
 *     This module only knows about Fabric. The pipeline coordinator
 *     in `texturePipeline.ts` is the SOLE site that mutates
 *     `threeTexture.needsUpdate`.
 *   - Rule R2: ZERO `console.*` statements; failures throw or return.
 *   - Rule R3: No imports of any Firebase, JWT, or auth packages — pure
 *     rendering utility.
 *
 * Out of scope:
 *   - Reading the canvas back into another bitmap or PNG (the texture
 *     pipeline reads the underlying HTMLCanvasElement directly via
 *     `canvas.getElement()` so the texture never needs a raster export).
 *   - Animations or rAF-driven Fabric animations — every render is
 *     triggered explicitly by the texture pipeline in response to a
 *     state change.
 */

import { StaticCanvas } from 'fabric';

// ---------------------------------------------------------------------------
// Module-level constants
// ---------------------------------------------------------------------------

/**
 * Texture canvas width in pixels. 2:1 ratio with height for clean
 * spherical wrapping. 1024 is high enough for legible logo art and
 * crisp panel boundaries; doubling to 2048 would quadruple GPU upload
 * cost on every frame the texture is marked `needsUpdate=true`.
 */
const FABRIC_CANVAS_WIDTH = 1024;

/**
 * Texture canvas height in pixels (half the width, matching the
 * equirectangular projection ratio used by the spherical UV mapping
 * generated by Three.js's `SphereGeometry`).
 */
const FABRIC_CANVAS_HEIGHT = 512;

// ---------------------------------------------------------------------------
// Module-private singleton state
//
// Module scope (not per-effect) so that React StrictMode's mount/cleanup/
// remount cycle does not create a duplicate Fabric canvas. Vite HMR may
// re-execute consuming components but never re-evaluates this module
// unless this file itself changes.
// ---------------------------------------------------------------------------

/**
 * The single Fabric.js StaticCanvas used by the texture pipeline.
 * `null` until `getFabricCanvas()` first creates it; reset to `null`
 * by `disposeFabricCanvas()`.
 */
let fabricCanvas: StaticCanvas | null = null;

/**
 * Native HTML `<canvas>` element backing `fabricCanvas`. Cached here
 * because Fabric's `getElement()` walks an internal proxy — caching
 * spares the texture pipeline from doing that on every frame.
 */
let fabricElement: HTMLCanvasElement | null = null;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Return the singleton Fabric canvas, creating it on first call.
 *
 * SSR-unsafe by design: this module is imported only by browser-side
 * texture pipeline code that runs after `window` is available. Calling
 * this function in a Node context (e.g. unit tests under jsdom) is
 * supported because `StaticCanvas` constructs a DOM-detached
 * `HTMLCanvasElement` via `document.createElement('canvas')`.
 *
 * The canvas is initialized with the documented default panel color
 * (`CONFIGURATOR_DEFAULTS.primaryColor`, '#FFFFFF') so the very first
 * texture upload — which happens on Sphere mount before any user
 * interaction — produces a visible white sphere rather than a checker-
 * board placeholder. The default color is hard-coded here rather than
 * imported from the store to keep this module decoupled from React /
 * Zustand and to preserve the singleton's initialization contract
 * (the store's defaults, the texture-pipeline's defaults, and the
 * Three material's defaults are kept in lockstep by code review and
 * by the tests in `tests/configurator/`).
 */
export function getFabricCanvas(): StaticCanvas {
  if (fabricCanvas !== null) {
    return fabricCanvas;
  }

  // `StaticCanvas` accepts an HTMLCanvasElement OR an element ID; passing
  // a freshly-created detached element keeps the canvas off-screen
  // (no DOM mounting required). Fabric will manage internal lifecycle
  // including its own pixel buffer and event delegation (which we
  // intentionally do not consume).
  const detachedElement = document.createElement('canvas');
  detachedElement.width = FABRIC_CANVAS_WIDTH;
  detachedElement.height = FABRIC_CANVAS_HEIGHT;

  fabricCanvas = new StaticCanvas(detachedElement, {
    width: FABRIC_CANVAS_WIDTH,
    height: FABRIC_CANVAS_HEIGHT,
    // Hex string is accepted by Fabric and is normalized internally to
    // its CSS-compatible `fill` property. Pure white matches
    // `CONFIGURATOR_DEFAULTS.primaryColor` so the initial texture is
    // visually correct without any further setup.
    backgroundColor: '#FFFFFF',
    // Fabric defaults `renderOnAddRemove` to `true` — meaning every
    // `add()` triggers an internal render. The texture pipeline calls
    // `renderAll()` exactly once per state change, so per-add renders
    // are wasted work. Disabling them halves the Fabric draw count
    // during multi-object mutations (e.g. logo + accent text).
    renderOnAddRemove: false,
    // The texture pipeline owns the rAF cadence; Fabric's internal
    // animation loop is unnecessary and would compete for CPU.
    enableRetinaScaling: false,
  });

  fabricElement = detachedElement;
  return fabricCanvas;
}

/**
 * Return the underlying HTMLCanvasElement. Used by `threeTexture.ts` to
 * construct the `THREE.CanvasTexture` that wraps Fabric's pixel buffer.
 *
 * Idempotent: returns the same element across multiple calls so that
 * the Three.js texture's source never changes mid-run (changing the
 * source mid-run would invalidate every GPU mipmap and cause a visible
 * flash on the first frame after the swap).
 */
export function getFabricElement(): HTMLCanvasElement {
  if (fabricElement === null) {
    // Eagerly trigger canvas creation; the side effect populates
    // `fabricElement`.
    getFabricCanvas();
  }
  // After `getFabricCanvas()` returns successfully, `fabricElement` is
  // guaranteed non-null. The non-null assertion documents that
  // post-condition for the type system.
  return fabricElement as HTMLCanvasElement;
}

/**
 * Render the Fabric canvas synchronously.
 *
 * This is the FIRST half of the C6 / R7 ordering contract:
 *
 *   1. fabricCanvas.renderAll()   ← THIS function
 *   2. threeTexture.needsUpdate = true   ← `markThreeTextureDirty()`
 *
 * Reversing this order produces a one-frame stale texture that surfaces
 * as a flicker in the Playwright visual-regression baselines (per AAP
 * C6: "Reversing this order produces a one-frame stale texture that is
 * visible as flicker").
 *
 * `StaticCanvas#renderAll()` is synchronous (it walks the object list
 * once and rasterizes into the underlying 2D context). The function
 * returns `void`; we wrap it here so callers depend on this module's
 * abstraction rather than directly on Fabric's API surface (which lets
 * us swap the rendering primitive in the future without touching the
 * pipeline coordinator).
 */
export function renderFabricCanvas(): void {
  // Calling `getFabricCanvas()` (instead of asserting on the cached
  // singleton) makes this function safe to call BEFORE
  // `getFabricElement()` has run — the worst case is that we lazily
  // create the canvas right here, render an empty scene, and the
  // texture pipeline still satisfies the order contract.
  const canvas = getFabricCanvas();
  canvas.renderAll();
}

/**
 * Dispose the Fabric canvas singleton.
 *
 * Idempotent: safe to call when no canvas exists. After invocation,
 * the next `getFabricCanvas()` / `getFabricElement()` call constructs
 * a fresh canvas — supporting the React StrictMode "mount → cleanup →
 * remount" cycle in development.
 *
 * Disposing also frees the underlying GPU resources tracked by Three.js
 * because the `CanvasTexture` referencing this element is disposed in
 * lockstep by `disposeThreeTexture()`.
 */
export function disposeFabricCanvas(): void {
  if (fabricCanvas !== null) {
    // `dispose()` is sync in Fabric 6 even though the type signature
    // shows `Promise<boolean>`. We don't await it because we have
    // nothing to do with the result — disposal is fire-and-forget.
    void fabricCanvas.dispose();
    fabricCanvas = null;
  }
  fabricElement = null;
}

/**
 * Read-only constant exports for documentation and tests.
 */
export const FABRIC_CANVAS_DIMENSIONS = {
  width: FABRIC_CANVAS_WIDTH,
  height: FABRIC_CANVAS_HEIGHT,
} as const;
